import 'package:new_vvvvid/models/comment.dart';
import 'package:new_vvvvid/models/episode.dart';
import 'package:new_vvvvid/models/products.dart';
import 'package:new_vvvvid/models/season.dart';

List<String> generi = ['Drammatico', 'Azione', 'Shonen', 'Comico'];

final DUMMY_PRODUCTS = [
  //Anime1-Hunter x Hunter

  Products.episodic(
      id: 1,
      title: 'Hunter x Hunter',
      previewImgUrl:
          'https://github.com/SimoneCalifano00/Progetto-VVVVID/raw/master/Asset/Hunter_x_Hunter_2011-cover.jpg',
      description:
          "Mostri, animali rari, tesori e meraviglie, terre selvagge e luoghi inesplorati. La parola 'sconosciuto' reca in sé un enorme fascino e vi sono persone incredibili al mondo attratte da tale potere. Esse sono conosciute con il nome di 'Hunter'! Gon vuole diventare uno di loro, come suo padre prima di lui, ma riuscirà in questa incredibile impresa?",
      comments: [
        Comment(creatorId: 1, text: 'Finale soddisfacente.'),
        Comment(creatorId: 2, text: 'N-non vedremo mai la fine...'),
        Comment(creatorId: 3, text: 'e meglio tokio ghul'),
        Comment(creatorId: 4, text: 'Belle animazioni!'),
      ],
      previewImgsUrls: [
        'https://github.com/SimoneCalifano00/Progetto-VVVVID/raw/master/Asset/Hunter_x_Hunter_2011-cover.jpg',
        'https://github.com/SimoneCalifano00/Progetto-VVVVID/raw/master/Asset/hxh2.jpg',
        'https://github.com/SimoneCalifano00/Progetto-VVVVID/raw/master/Asset/hxh1.jpg',
      ],
      date: DateTime.utc(2011, 10, 2),
      seasons: [
        Season(sNumber: 1, nEpisodes: 36, episodes: [
          Episode(nEpisode: 1, title: 'Partenza e compagni'),
          Episode(nEpisode: 2, title: "L'esame dell'esame"),
          Episode(nEpisode: 3, title: "Rivali per la sopravvivenza"),
          Episode(nEpisode: 4, title: "Speranza e ambizione"),
          Episode(nEpisode: 5, title: 'Partenza e compagni'),
          Episode(nEpisode: 6, title: 'Partenza e compagni'),
          Episode(nEpisode: 7, title: 'Partenza e compagni'),
          Episode(nEpisode: 8, title: 'Partenza e compagni'),
          Episode(nEpisode: 9, title: 'Partenza e compagni'),
          Episode(nEpisode: 10, title: 'Partenza e compagni'),
          Episode(nEpisode: 11, title: 'Partenza e compagni'),
          Episode(nEpisode: 12, title: 'Partenza e compagni'),
          Episode(nEpisode: 13, title: 'Partenza e compagni'),
          Episode(nEpisode: 14, title: 'Partenza e compagni'),
          Episode(nEpisode: 15, title: 'Partenza e compagni'),
          Episode(nEpisode: 16, title: 'Partenza e compagni'),
          Episode(nEpisode: 17, title: 'Partenza e compagni'),
          Episode(nEpisode: 19, title: 'Partenza e compagni'),
          Episode(nEpisode: 19, title: 'Partenza e compagni'),
          Episode(nEpisode: 20, title: 'Partenza e compagni'),
          Episode(nEpisode: 21, title: 'Partenza e compagni'),
          Episode(nEpisode: 22, title: 'Partenza e compagni'),
          Episode(nEpisode: 23, title: ''),
          Episode(nEpisode: 24, title: ''),
          Episode(nEpisode: 25, title: ''),
          Episode(nEpisode: 26, title: ''),
          Episode(nEpisode: 27, title: ''),
          Episode(nEpisode: 28, title: ''),
          Episode(nEpisode: 29, title: ''),
          Episode(nEpisode: 30, title: ''),
          Episode(nEpisode: 31, title: ''),
          Episode(nEpisode: 32, title: ''),
          Episode(nEpisode: 33, title: ''),
          Episode(nEpisode: 34, title: ''),
          Episode(nEpisode: 35, title: ''),
          Episode(nEpisode: 36, title: ''),
        ]),
        Season(sNumber: 2, nEpisodes: 39, episodes: [
          Episode(nEpisode: 1, title: 'Partenza e compagni'),
          Episode(nEpisode: 2, title: "L'esame dell'esame"),
          Episode(nEpisode: 3, title: "Rivali per la sopravvivenza"),
          Episode(nEpisode: 4, title: "Speranza e ambizione"),
          Episode(nEpisode: 5, title: 'Partenza e compagni'),
          Episode(nEpisode: 6, title: 'Partenza e compagni'),
          Episode(nEpisode: 7, title: 'Partenza e compagni'),
          Episode(nEpisode: 8, title: 'Partenza e compagni'),
          Episode(nEpisode: 9, title: 'Partenza e compagni'),
          Episode(nEpisode: 10, title: 'Partenza e compagni'),
          Episode(nEpisode: 11, title: 'Partenza e compagni'),
          Episode(nEpisode: 12, title: 'Partenza e compagni'),
          Episode(nEpisode: 13, title: 'Partenza e compagni'),
          Episode(nEpisode: 14, title: 'Partenza e compagni'),
          Episode(nEpisode: 15, title: 'Partenza e compagni'),
          Episode(nEpisode: 16, title: 'Partenza e compagni'),
          Episode(nEpisode: 17, title: 'Partenza e compagni'),
          Episode(nEpisode: 19, title: 'Partenza e compagni'),
          Episode(nEpisode: 19, title: 'Partenza e compagni'),
          Episode(nEpisode: 20, title: 'Partenza e compagni'),
          Episode(nEpisode: 21, title: 'Partenza e compagni'),
          Episode(nEpisode: 22, title: 'Partenza e compagni'),
          Episode(nEpisode: 23, title: ''),
          Episode(nEpisode: 24, title: ''),
          Episode(nEpisode: 25, title: ''),
          Episode(nEpisode: 26, title: ''),
          Episode(nEpisode: 27, title: ''),
          Episode(nEpisode: 28, title: ''),
          Episode(nEpisode: 29, title: ''),
          Episode(nEpisode: 30, title: ''),
          Episode(nEpisode: 31, title: ''),
          Episode(nEpisode: 32, title: ''),
          Episode(nEpisode: 33, title: ''),
          Episode(nEpisode: 34, title: ''),
          Episode(nEpisode: 35, title: ''),
          Episode(nEpisode: 36, title: ''),
          Episode(nEpisode: 37, title: ''),
          Episode(nEpisode: 38, title: ''),
          Episode(nEpisode: 39, title: ''),
        ]),
        Season(sNumber: 3, nEpisodes: 73, episodes: [
          Episode(nEpisode: 1, title: 'Partenza e compagni'),
          Episode(nEpisode: 2, title: "L'esame dell'esame"),
          Episode(nEpisode: 3, title: "Rivali per la sopravvivenza"),
          Episode(nEpisode: 4, title: "Speranza e ambizione"),
          Episode(nEpisode: 5, title: 'Partenza e compagni'),
          Episode(nEpisode: 6, title: 'Partenza e compagni'),
          Episode(nEpisode: 7, title: 'Partenza e compagni'),
          Episode(nEpisode: 8, title: 'Partenza e compagni'),
          Episode(nEpisode: 9, title: 'Partenza e compagni'),
          Episode(nEpisode: 10, title: 'Partenza e compagni'),
          Episode(nEpisode: 11, title: 'Partenza e compagni'),
          Episode(nEpisode: 12, title: 'Partenza e compagni'),
          Episode(nEpisode: 13, title: 'Partenza e compagni'),
          Episode(nEpisode: 14, title: 'Partenza e compagni'),
          Episode(nEpisode: 15, title: 'Partenza e compagni'),
          Episode(nEpisode: 16, title: 'Partenza e compagni'),
          Episode(nEpisode: 17, title: 'Partenza e compagni'),
          Episode(nEpisode: 19, title: 'Partenza e compagni'),
          Episode(nEpisode: 19, title: 'Partenza e compagni'),
          Episode(nEpisode: 20, title: 'Partenza e compagni'),
          Episode(nEpisode: 21, title: 'Partenza e compagni'),
          Episode(nEpisode: 22, title: 'Partenza e compagni'),
          Episode(nEpisode: 23, title: ''),
          Episode(nEpisode: 24, title: ''),
          Episode(nEpisode: 25, title: ''),
          Episode(nEpisode: 26, title: ''),
          Episode(nEpisode: 27, title: ''),
          Episode(nEpisode: 28, title: ''),
          Episode(nEpisode: 29, title: ''),
          Episode(nEpisode: 30, title: ''),
          Episode(nEpisode: 31, title: ''),
          Episode(nEpisode: 32, title: ''),
          Episode(nEpisode: 33, title: ''),
          Episode(nEpisode: 34, title: ''),
          Episode(nEpisode: 35, title: ''),
          Episode(nEpisode: 36, title: ''),
          Episode(nEpisode: 37, title: ''),
          Episode(nEpisode: 38, title: ''),
          Episode(nEpisode: 39, title: ''),
          Episode(nEpisode: 40, title: ''),
          Episode(nEpisode: 41, title: ''),
          Episode(nEpisode: 42, title: ''),
          Episode(nEpisode: 43, title: ''),
          Episode(nEpisode: 44, title: ''),
          Episode(nEpisode: 45, title: ''),
          Episode(nEpisode: 46, title: ''),
          Episode(nEpisode: 47, title: ''),
          Episode(nEpisode: 48, title: ''),
          Episode(nEpisode: 49, title: ''),
          Episode(nEpisode: 50, title: ''),
          Episode(nEpisode: 51, title: ''),
          Episode(nEpisode: 52, title: ''),
          Episode(nEpisode: 53, title: ''),
          Episode(nEpisode: 54, title: ''),
          Episode(nEpisode: 55, title: ''),
          Episode(nEpisode: 56, title: ''),
          Episode(nEpisode: 57, title: ''),
          Episode(nEpisode: 58, title: ''),
          Episode(nEpisode: 59, title: ''),
          Episode(nEpisode: 60, title: ''),
          Episode(nEpisode: 61, title: ''),
          Episode(nEpisode: 62, title: ''),
          Episode(nEpisode: 63, title: ''),
          Episode(nEpisode: 64, title: ''),
          Episode(nEpisode: 65, title: ''),
          Episode(nEpisode: 66, title: ''),
          Episode(nEpisode: 67, title: ''),
          Episode(nEpisode: 68, title: ''),
          Episode(nEpisode: 69, title: ''),
          Episode(nEpisode: 70, title: ''),
          Episode(nEpisode: 71, title: ''),
          Episode(nEpisode: 72, title: ''),
          Episode(nEpisode: 73, title: ''),
        ]),
      ],
      genere: Genere.Azione,
      generi: ['Drammatico', 'Azione', 'Shonen'],
      sezione: Sezione.Anime)
];
